
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package LOGICA.Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int Tid = 13;
  public static final int Rbool = 10;
  public static final int Tsep = 6;
  public static final int Tcadena = 19;
  public static final int Tmayor = 23;
  public static final int Tfin_si = 21;
  public static final int Rint = 12;
  public static final int Tnumero = 18;
  public static final int Tfin = 8;
  public static final int Tsi = 20;
  public static final int Tmas = 14;
  public static final int Tentonces = 2;
  public static final int Tmayor_igual = 24;
  public static final int EOF = 0;
  public static final int Tentonces_si = 28;
  public static final int Tmenos = 15;
  public static final int Tmenor = 22;
  public static final int Tentre = 17;
  public static final int error = 1;
  public static final int Tigual = 27;
  public static final int Tleer = 5;
  public static final int Tini = 7;
  public static final int Tpor = 16;
  public static final int Rdeci = 9;
  public static final int Tdifer = 26;
  public static final int Rcade = 11;
  public static final int Tmenor_igual = 25;
  public static final int Tmostrar = 4;
  public static final int Tasign = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Tentonces",
  "Tasign",
  "Tmostrar",
  "Tleer",
  "Tsep",
  "Tini",
  "Tfin",
  "Rdeci",
  "Rbool",
  "Rcade",
  "Rint",
  "Tid",
  "Tmas",
  "Tmenos",
  "Tpor",
  "Tentre",
  "Tnumero",
  "Tcadena",
  "Tsi",
  "Tfin_si",
  "Tmenor",
  "Tmayor",
  "Tmayor_igual",
  "Tmenor_igual",
  "Tdifer",
  "Tigual",
  "Tentonces_si"
  };
}

