
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package LOGICA.Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int Tsep = 13;
  public static final int Tmenosmenos = 3;
  public static final int Tasign = 10;
  public static final int Tpor = 23;
  public static final int Tdifer = 33;
  public static final int Tmientras = 6;
  public static final int Tentre = 24;
  public static final int Tcadena = 26;
  public static final int Tcoma = 8;
  public static final int Tmostrar = 11;
  public static final int Tfin = 15;
  public static final int Rcade = 18;
  public static final int Tfin_para = 5;
  public static final int Tini = 14;
  public static final int Tfin_mientras = 7;
  public static final int Rint = 19;
  public static final int Tleer = 12;
  public static final int EOF = 0;
  public static final int Rdeci = 16;
  public static final int Tpara = 4;
  public static final int error = 1;
  public static final int Tigual = 34;
  public static final int Rbool = 17;
  public static final int Tentonces_si = 35;
  public static final int Tsi = 27;
  public static final int Tnumero = 25;
  public static final int Tmasmas = 2;
  public static final int Tfin_si = 28;
  public static final int Tmayor_igual = 31;
  public static final int Tmenos = 22;
  public static final int Tmenor = 29;
  public static final int Tmenor_igual = 32;
  public static final int Tmayor = 30;
  public static final int Tid = 20;
  public static final int Tentonces = 9;
  public static final int Tmas = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Tmasmas",
  "Tmenosmenos",
  "Tpara",
  "Tfin_para",
  "Tmientras",
  "Tfin_mientras",
  "Tcoma",
  "Tentonces",
  "Tasign",
  "Tmostrar",
  "Tleer",
  "Tsep",
  "Tini",
  "Tfin",
  "Rdeci",
  "Rbool",
  "Rcade",
  "Rint",
  "Tid",
  "Tmas",
  "Tmenos",
  "Tpor",
  "Tentre",
  "Tnumero",
  "Tcadena",
  "Tsi",
  "Tfin_si",
  "Tmenor",
  "Tmayor",
  "Tmayor_igual",
  "Tmenor_igual",
  "Tdifer",
  "Tigual",
  "Tentonces_si"
  };
}

